version: '3.9'
services:

  #MYSQL
  mysql:
    build: "./docker/mysql"
    container_name: "${appName}-mysql"
    restart: "always"
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      [
        "mysqld",
        "--max_allowed_packet=32505856",
        "--sql_mode="
      ]
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"

  #APACHE-PHP
  apache-php:
    build: "./docker/apache-php/"
    container_name: "${appName}-apache-php"
    restart: "always"
    ports:
      - "${PORT_HTTP}:80"
    depends_on:
      - mysql
    volumes:
      #pasta do sistema
      - "./app:/var/www/html"
      #configurações php
      - "./docker/apache-php/php-conf:/usr/local/etc/php"
